name: Build Android Debug APK (React Native)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (uses .nvmrc if present, else 18)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install JS dependencies
        run: |
          if [ -f yarn.lock ]; then
            corepack enable
            yarn --frozen-lockfile || yarn
          elif [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm i --frozen-lockfile || pnpm i
          else
            npm ci || npm i
          fi

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      # 安装 Android SDK 组件（与 RN 默认 compileSdk/ buildTools 对齐）
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Make gradlew executable
        working-directory: android
        run: chmod +x ./gradlew

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Locate APKs
        id: locate
        run: |
          echo "apk_path=$(find android/app/build/outputs/apk -type f -name '*.*_
